[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

[etherscan]
mainnet = { key = "${POLYGONSCAN_API_KEY}", chain = "polygon", url = "https://api.polygonscan.com" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
