name: test

on: # and a condition on commit (example: it must contain "release")
  push:
    branches: [main]
  pull_request:

jobs:
  forge-test:
    strategy:
      fail-fast: true
    name: WeSplit tests
    runs-on: ubuntu-latest
    env:
      ALCHEMY_KEY: ${{ secrets.ALCHEMY_KEY }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Run Forge tests
        run: |
          make test
        id: test
  storage-check:
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest
    name: WeSplit storage check
      - name: Check proxy storage
        run: |
          make storage-check
        id: storage-check
