name: test

on: # and a condition on commit (example: it must contain "release")
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: ./.github/actions/ci
      - name: Build and check contract size
        run: make build
  forge-tests:
    needs: build
    runs-on: ubuntu-latest
    env:
      ALCHEMY_KEY: ${{ secrets.ALCHEMY_KEY }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: ./.github/actions/ci
      - name: Run Forge tests
        run: make test
  storage-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: ./.github/actions/ci
      - name: Check proxy storage
        run: make storage-check
