name: WeSplit CI

on: # and a condition on commit (example: it must contain "release")
  push:
    branches: [main]
  pull_request:

jobs:
  storage-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: storage-check
        run: make storage-check

  forge-test:
    needs: storage-check
    runs-on: ubuntu-latest
    env:
      ALCHEMY_KEY: ${{ secrets.ALCHEMY_KEY }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Build contracts and check sizes
        run: make build

      - name: Run Forge tests
        run: make test
